# Generated by Django 5.1 on 2024-10-04 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0003_alter_experience_category_alter_experience_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='perk',
            field=models.ManyToManyField(related_name='experiences', to='experiences.perk'),
        ),
    ]
