# Generated by Django 5.1 on 2024-10-04 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_experience_alter_booking_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='guests',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
